name: version check

permissions:
  contents: read

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Version check
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
            grep -E 'const version =' build.zig | grep -E "\"${TAG_NAME}\"" || exit 78
            echo "Zig build version check passed."
            grep -E "project\(aegis.*VERSION ${TAG_NAME}.*\)" CMakeLists.txt || exit 78
            echo "CMake version check passed."
